### ISSUE TITLE
Module not found: Error: Can't resolve 'xxx/xxx' in libraraian/...

### ISSUE THREAD

**Issue by karawitan** [portah/librarian#3]
Hi !

  thanks for sharing your indexer. I hope I'll be able to test and maybe propose patches sooner or later.
May I ask you for some help about this issue ?

npm run start leads to various errors of the form:
```
ERROR in ./src/lib/tracking.ts
Module not found: Error: Can't resolve 'xxx/xxx' in '/home/karawitan/librarian/src/lib'
```
Which suggests that module "xxx/xxx" is not installed ... then I tried to install the modules, with no success.

List of modules that seem to be missing:

```
ERROR in ./src/lib/pagination.ts
Module not found: Error: Can't resolve 'meteor/mongo' in '/home/karawitan/librarian/src/lib'

ERROR in ./src/app/books.service.ts
Module not found: Error: Can't resolve 'meteor/ostrio:files' in '/home/karawitan/librarian/src/app'

ERROR in ./src/lib/base.component.ts
Module not found: Error: Can't resolve 'meteor/random' in '/home/karawitan/librarian/src/lib'

ERROR in ./src/lib/tracking.ts
Module not found: Error: Can't resolve 'meteor/tracker' in '/home/karawitan/librarian/src/lib'
```

**Comment by portah** [comment]
oh, looks like meteor js issue. I'll take a look in the morning have not returned to the project for a long time.

**Comment by portah** [comment]
You have to install meteor.js locally 
Each npm install something would require this steps
```
npm run client-bundle
```
This command will create meteor-client.js in the root of the project but also a directory ./node_modules/meteor/ with tons of files.

For some projects I just zipped that directory and unzip it after each `npm install`

**Comment by karawitan** [comment]
Ok thank you ! Indeed when applying the instructions from the README it works better :-)
